# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180104_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
