# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180104_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='dateTime',
            new_name='date_time',
        ),
    ]
