# Generated by Django 2.0.1 on 2018-01-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180107_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Species', to_field='name'),
        ),
    ]
