# Generated by Django 2.0.1 on 2018-01-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180110_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
