# Generated by Django 2.0.1 on 2018-01-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180111_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='species',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Species', to_field='name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(default='', max_length=100, null=True, unique=True),
        ),
    ]
